global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'laravel'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['web:8001']
